# Generated by Django 5.2.7 on 2026-02-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='otp_code',
            field=models.CharField(db_index=True, default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='otp_code',
            field=models.CharField(db_index=True, default='000000', max_length=6),
        ),
    ]
