from django.urls import path

from courses.views import (
    AdminEnrollmentDetailView,
    AdminEnrollmentsView,
    AdminLessonDetailView,
    AdminLessonListCreateView,
    AdminQuizDetailView,
    AdminQuizListCreateView,
    AdminQuizQuestionCreateView,
    AdminQuizQuestionDetailView,
    AdminQuizQuestionImportView,
    AdminReviewDetailView,
    AdminReviewsView,
    CategoryListCreateView,
    CategoryRetrieveUpdateDestroyView,
    CourseListCreateView,
    CourseRetrieveUpdateDestroyView,
    CourseReviewsView,
    LearnerLessonDetailView,
    LearnerLessonPdfView,
    LearnerLessonProgressView,
    LearnerLessonThumbnailView,
    LearnerLessonVideoView,
    LearnerLMSOverviewView,
    LearnerQuizAnswerView,
    LearnerQuizAttemptDetailView,
    LearnerQuizListView,
    LearnerQuizStartView,
    LearnerQuizSubmitView,
    MyEnrollmentsView,
    RelatedCoursesView,
    ReviewVoteView,
)

urlpatterns = [
    path("categories/", CategoryListCreateView.as_view(), name="categories"),
    path("categories/<int:pk>/", CategoryRetrieveUpdateDestroyView.as_view(), name="category-detail"),
    path("", CourseListCreateView.as_view(), name="courses"),
    path("<int:pk>/", CourseRetrieveUpdateDestroyView.as_view(), name="course-detail"),
    path("<int:course_id>/related/", RelatedCoursesView.as_view(), name="course-related"),
    path("<int:course_id>/reviews/", CourseReviewsView.as_view(), name="course-reviews"),
    path("reviews/<int:review_id>/vote/", ReviewVoteView.as_view(), name="review-vote"),
    path("enrollments/me/", MyEnrollmentsView.as_view(), name="my-enrollments"),
    path("admin/enrollments/", AdminEnrollmentsView.as_view(), name="admin-enrollments"),
    path("admin/enrollments/<int:enrollment_id>/", AdminEnrollmentDetailView.as_view(), name="admin-enrollment-detail"),
    path("admin/reviews/", AdminReviewsView.as_view(), name="admin-reviews"),
    path("admin/reviews/<int:review_id>/", AdminReviewDetailView.as_view(), name="admin-review-detail"),
    path("admin/lms-lessons/", AdminLessonListCreateView.as_view(), name="admin-lms-lessons"),
    path("admin/lms-lessons/<int:lesson_id>/", AdminLessonDetailView.as_view(), name="admin-lms-lesson-detail"),
    path("admin/quizzes/", AdminQuizListCreateView.as_view(), name="admin-quizzes"),
    path("admin/quizzes/<int:quiz_id>/", AdminQuizDetailView.as_view(), name="admin-quiz-detail"),
    path("admin/quizzes/<int:quiz_id>/questions/", AdminQuizQuestionCreateView.as_view(), name="admin-quiz-questions"),
    path("admin/quizzes/<int:quiz_id>/questions/import/", AdminQuizQuestionImportView.as_view(), name="admin-quiz-question-import"),
    path("admin/quiz-questions/<int:question_id>/", AdminQuizQuestionDetailView.as_view(), name="admin-quiz-question-detail"),
    path("lms/<int:course_id>/overview/", LearnerLMSOverviewView.as_view(), name="learner-lms-overview"),
    path("lms/<int:course_id>/quizzes/", LearnerQuizListView.as_view(), name="learner-quizzes"),
    path("lms/lessons/<int:lesson_id>/", LearnerLessonDetailView.as_view(), name="learner-lesson-detail"),
    path("lms/lessons/<int:lesson_id>/pdf/", LearnerLessonPdfView.as_view(), name="learner-lesson-pdf"),
    path("lms/lessons/<int:lesson_id>/video/", LearnerLessonVideoView.as_view(), name="learner-lesson-video"),
    path("lms/lessons/<int:lesson_id>/thumbnail/", LearnerLessonThumbnailView.as_view(), name="learner-lesson-thumbnail"),
    path("lms/lessons/<int:lesson_id>/progress/", LearnerLessonProgressView.as_view(), name="learner-lesson-progress"),
    path("lms/quizzes/<int:quiz_id>/start/", LearnerQuizStartView.as_view(), name="learner-quiz-start"),
    path("lms/quiz-attempts/<int:attempt_id>/", LearnerQuizAttemptDetailView.as_view(), name="learner-quiz-attempt"),
    path("lms/quiz-attempts/<int:attempt_id>/answer/", LearnerQuizAnswerView.as_view(), name="learner-quiz-answer"),
    path("lms/quiz-attempts/<int:attempt_id>/submit/", LearnerQuizSubmitView.as_view(), name="learner-quiz-submit"),
]
