from django.urls import path

from courses.views import (
    AdminEnrollmentDetailView,
    AdminEnrollmentsView,
    AdminLessonDetailView,
    AdminLessonListCreateView,
    AdminReviewDetailView,
    AdminReviewsView,
    CategoryListCreateView,
    CategoryRetrieveUpdateDestroyView,
    CourseListCreateView,
    CourseRetrieveUpdateDestroyView,
    CourseReviewsView,
    LearnerLessonDetailView,
    LearnerLessonProgressView,
    LearnerLMSOverviewView,
    MyEnrollmentsView,
    RelatedCoursesView,
    ReviewVoteView,
)

urlpatterns = [
    path("categories/", CategoryListCreateView.as_view(), name="categories"),
    path("categories/<int:pk>/", CategoryRetrieveUpdateDestroyView.as_view(), name="category-detail"),
    path("", CourseListCreateView.as_view(), name="courses"),
    path("<int:pk>/", CourseRetrieveUpdateDestroyView.as_view(), name="course-detail"),
    path("<int:course_id>/related/", RelatedCoursesView.as_view(), name="course-related"),
    path("<int:course_id>/reviews/", CourseReviewsView.as_view(), name="course-reviews"),
    path("reviews/<int:review_id>/vote/", ReviewVoteView.as_view(), name="review-vote"),
    path("enrollments/me/", MyEnrollmentsView.as_view(), name="my-enrollments"),
    path("admin/enrollments/", AdminEnrollmentsView.as_view(), name="admin-enrollments"),
    path("admin/enrollments/<int:enrollment_id>/", AdminEnrollmentDetailView.as_view(), name="admin-enrollment-detail"),
    path("admin/reviews/", AdminReviewsView.as_view(), name="admin-reviews"),
    path("admin/reviews/<int:review_id>/", AdminReviewDetailView.as_view(), name="admin-review-detail"),
    path("admin/lms-lessons/", AdminLessonListCreateView.as_view(), name="admin-lms-lessons"),
    path("admin/lms-lessons/<int:lesson_id>/", AdminLessonDetailView.as_view(), name="admin-lms-lesson-detail"),
    path("lms/<int:course_id>/overview/", LearnerLMSOverviewView.as_view(), name="learner-lms-overview"),
    path("lms/lessons/<int:lesson_id>/", LearnerLessonDetailView.as_view(), name="learner-lesson-detail"),
    path("lms/lessons/<int:lesson_id>/progress/", LearnerLessonProgressView.as_view(), name="learner-lesson-progress"),
]
