# Generated by Django 5.2.7 on 2026-07-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blog',
            new_name='blog_blog_slug_d925e3_idx',
            old_name='blog_blog_slug_09b499_idx',
        ),
        migrations.RenameIndex(
            model_name='blog',
            new_name='blog_blog_status_09fb7c_idx',
            old_name='blog_blog_status_434082_idx',
        ),
        migrations.RenameIndex(
            model_name='blog',
            new_name='blog_blog_course__158a3a_idx',
            old_name='blog_blog_course__443c8f_idx',
        ),
        migrations.RenameIndex(
            model_name='blog',
            new_name='blog_blog_is_feat_768fbc_idx',
            old_name='blog_blog_is_feat_9026c3_idx',
        ),
    ]
