# Generated by Django 5.2.7 on 2026-07-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_blog_slug_09b499_idx_blog_blog_slug_d925e3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/heroes/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='section_images',
            field=models.ManyToManyField(blank=True, related_name='section_blogs', to='blog.blogimage'),
        ),
    ]
