# Generated by Django 5.2.7 on 2026-07-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_hero_image_blog_section_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='placement',
            field=models.CharField(choices=[('introduction', 'Introduction'), ('modules', 'Modules'), ('related', 'Related Articles')], default='introduction', max_length=32),
        ),
    ]
