# Generated by Django 5.2.7 on 2026-07-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogimage_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
