# Generated by Django 5.2.7 on 2026-07-07 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogimage_caption'),
        ('courses', '0015_rename_courses_cou_slug_8f042f_idx_courses_cou_slug_2e551f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], db_index=True, default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='series_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='series_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['difficulty'], name='blog_blog_difficu_0f1075_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['series_name', 'series_order'], name='blog_blog_series__6b9858_idx'),
        ),
    ]
