# Generated by Django 5.2.7 on 2026-07-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_difficulty_blog_series_name_blog_series_order_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blog',
            name='blog_blog_difficu_0f1075_idx',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='difficulty',
        ),
    ]
