# Generated by Django 5.2.7 on 2026-02-23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentage discount applied before tax.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
