# Generated by Django 5.2.7 on 2026-02-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mentor_bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='mentor_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='course',
            name='mentor_title',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
