# Generated by Django 5.2.7 on 2026-02-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_mentor_bio_course_mentor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Estimated learning plan duration in days.'),
        ),
    ]
