# Generated by Django 5.2.7 on 2026-05-08 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_mentor_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.PositiveSmallIntegerField()),
                ('lesson_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(max_length=1200)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['module_number', 'lesson_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_items', to='courses.courselesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='courselesson',
            index=models.Index(fields=['course', 'is_active'], name='courses_cou_course__4c7f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='courselesson',
            index=models.Index(fields=['course', 'module_number', 'lesson_number'], name='courses_cou_course__10adc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courselesson',
            unique_together={('course', 'module_number', 'lesson_number')},
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'is_completed'], name='courses_use_user_id_d303bb_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'lesson'], name='courses_use_user_id_6cda79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together={('user', 'lesson')},
        ),
    ]
