# Generated by Django 5.2.7 on 2026-07-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_catalog_metadata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='courses_cou_slug_2e551f_idx',
            old_name='courses_cou_slug_8f042f_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='courses_cou_order_4f7c74_idx',
            old_name='courses_cou_order_e650c7_idx',
        ),
        migrations.AddField(
            model_name='course',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
