# Generated by Django 5.2.7 on 2026-03-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_replace_stripe_with_razorpay_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payments_pa_razorpa_c4e21c_idx',
            old_name='payments_pa_razorpa_17870d_idx',
        ),
    ]
